# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # match(type: "appstore", app_identifier: "com.springbig.merchant-2-test", readonly: true)
    increment_build_number(xcodeproj: "merchant-2-test.xcodeproj")
    build_app(scheme: "merchant-2-test", output_name: "Merchant2.ipa")
    upload_to_testflight(ipa: "Merchant2.ipa", skip_metadata: true, skip_screenshots: true, force: true)
  end
end
